[package]
name = "atrinik-render-wgpu"
description = "Private Vulkan and D3D12 wgpu renderer for Atrinik"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
atrinik-render-api.workspace = true
atrinik-render-resources.workspace = true
atrinik-scene.workspace = true
bytemuck.workspace = true
pollster.workspace = true
wgpu.workspace = true

[dev-dependencies]
atrinik-render-testkit.workspace = true
naga.workspace = true

[lints]
workspace = true
